---
title: Voeg een "wrapped" sectie toe bij brede en smalle elementen
hero_image: images/banner.png
description: Voeg een "wrapped" sectie toe bij brede en smalle elementen.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Voeg een "wrapped" sectie toe bij brede en smalle elementen
